name: CI
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: nikeee/setup-pandoc@v1
      with:
        pandoc-version: '3.1.2'
    - name: Convert
      run: |
        bash ./convert.sh
    - uses: actions/upload-artifact@v3
      with:
        name: blog-html
        path: '*.html'
